
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: ellen
    password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update


